### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by liveforeverx** [ericmj/ex2ms#23]
May be we can release new version with record support?

**Comment by lud** [comment]
Buuuuump ! It would be good if the last bug fixes were published on hex.pm :)

**Comment by montanonic** [comment]
Yes, are there any significant reasons a version bump is being held off? I've pulled master for this on my project because of the support for action functions existing only on master.

That's IMO a pretty critical part of match expressions and it feels very important to have that available as a new version off of master.

Let us know what stuff might need to be fixed before a new release if you'd like any help @ericmj :)

**Comment by ericmj** [comment]
1.6.0 has been released.
